app:
  name: "web_cli"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "web_cli.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "root1234"
  dbname: "sql_demo"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 16379
  db: 0
  password: ""
  pool_size: 0